CREATE TABLE photos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED DEFAULT NULL,
	url VARCHAR(200) NOT NULL,
	name VARCHAR(30) NOT NULL,
	description TEXT,
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL
);