CREATE TABLE forms (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
	url VARCHAR(200) NOT NULL,
	description TEXT,
    user_id INT UNSIGNED DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL
);